name: Test (megalodon)

on:
  push:
    branches:
      - master
      - develop
    paths:
      - packages/megalodon/**
      - .github/workflows/test-megalodon.yml
  pull_request:
    branches-ignore:
      - master
    paths:
      - packages/megalodon/**
      - .github/workflows/test-megalodon.yml

jobs:
  test:
    name: Unit tests (megalodon)

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Setup pnpm
        uses: pnpm/action-setup@v6.0.10

      - name: Setup Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Test
        run: pnpm --filter megalodon test
        env:
          CI: true
